# -*- coding: utf-8 -*-
{
    'name': "l10n_co_location",

    'summary': "Colombian info",

    'description': """
This module loads:
- colombian gegraphical information (states and cities).
Further, it loads the code for each city and state generated by the DANE.
- Colombian Banks

""",
    'author': "CTI Ltda",
    'contributor': "Carlos Martínez Camelo",
    # 'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'res_partner',
    'version': '1.0',
    'sequence': 30,
    # any module necessary for this one to work correctlyi
    'depends': ['base'],
    # always loaded
    'data': [
        'data/res.bank.csv',
        'data/res.country.state.csv',
        'data/res.country.state.city.csv',
        'security/ir.model.access.csv',
        'views/partner_city_view.xml',
        'views/bank_city_view.xml',
        'views/company_city_view.xml',
    ],
    # only loaded in demonstration mode
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
